# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luca/shared-folder/lfbgs-2-lbfgs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luca/shared-folder/lfbgs-2-lbfgs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/shared-folder/lfbgs-2-lbfgs/CMakeFiles /home/luca/shared-folder/lfbgs-2-lbfgs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/shared-folder/lfbgs-2-lbfgs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lbfgs_lib

# Build rule for target.
lbfgs_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lbfgs_lib
.PHONY : lbfgs_lib

# fast build rule for target.
lbfgs_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/build
.PHONY : lbfgs_lib/fast

#=============================================================================
# Target rules for targets named test_bfgs

# Build rule for target.
test_bfgs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bfgs
.PHONY : test_bfgs

# fast build rule for target.
test_bfgs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bfgs.dir/build.make CMakeFiles/test_bfgs.dir/build
.PHONY : test_bfgs/fast

#=============================================================================
# Target rules for targets named test_lbfgs

# Build rule for target.
test_lbfgs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lbfgs
.PHONY : test_lbfgs

# fast build rule for target.
test_lbfgs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/build
.PHONY : test_lbfgs/fast

#=============================================================================
# Target rules for targets named test_gradient

# Build rule for target.
test_gradient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gradient
.PHONY : test_gradient

# fast build rule for target.
test_gradient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradient.dir/build.make CMakeFiles/test_gradient.dir/build
.PHONY : test_gradient/fast

#=============================================================================
# Target rules for targets named test_linesearch

# Build rule for target.
test_linesearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_linesearch
.PHONY : test_linesearch

# fast build rule for target.
test_linesearch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linesearch.dir/build.make CMakeFiles/test_linesearch.dir/build
.PHONY : test_linesearch/fast

src/BFGS.o: src/BFGS.cpp.o
.PHONY : src/BFGS.o

# target to build an object file
src/BFGS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/BFGS.cpp.o
.PHONY : src/BFGS.cpp.o

src/BFGS.i: src/BFGS.cpp.i
.PHONY : src/BFGS.i

# target to preprocess a source file
src/BFGS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/BFGS.cpp.i
.PHONY : src/BFGS.cpp.i

src/BFGS.s: src/BFGS.cpp.s
.PHONY : src/BFGS.s

# target to generate assembly for a file
src/BFGS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/BFGS.cpp.s
.PHONY : src/BFGS.cpp.s

src/utils/LineSearch.o: src/utils/LineSearch.cpp.o
.PHONY : src/utils/LineSearch.o

# target to build an object file
src/utils/LineSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/utils/LineSearch.cpp.o
.PHONY : src/utils/LineSearch.cpp.o

src/utils/LineSearch.i: src/utils/LineSearch.cpp.i
.PHONY : src/utils/LineSearch.i

# target to preprocess a source file
src/utils/LineSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/utils/LineSearch.cpp.i
.PHONY : src/utils/LineSearch.cpp.i

src/utils/LineSearch.s: src/utils/LineSearch.cpp.s
.PHONY : src/utils/LineSearch.s

# target to generate assembly for a file
src/utils/LineSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lbfgs_lib.dir/build.make CMakeFiles/lbfgs_lib.dir/src/utils/LineSearch.cpp.s
.PHONY : src/utils/LineSearch.cpp.s

test/bfgs.o: test/bfgs.cpp.o
.PHONY : test/bfgs.o

# target to build an object file
test/bfgs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bfgs.dir/build.make CMakeFiles/test_bfgs.dir/test/bfgs.cpp.o
.PHONY : test/bfgs.cpp.o

test/bfgs.i: test/bfgs.cpp.i
.PHONY : test/bfgs.i

# target to preprocess a source file
test/bfgs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bfgs.dir/build.make CMakeFiles/test_bfgs.dir/test/bfgs.cpp.i
.PHONY : test/bfgs.cpp.i

test/bfgs.s: test/bfgs.cpp.s
.PHONY : test/bfgs.s

# target to generate assembly for a file
test/bfgs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bfgs.dir/build.make CMakeFiles/test_bfgs.dir/test/bfgs.cpp.s
.PHONY : test/bfgs.cpp.s

test/gradient.o: test/gradient.cpp.o
.PHONY : test/gradient.o

# target to build an object file
test/gradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradient.dir/build.make CMakeFiles/test_gradient.dir/test/gradient.cpp.o
.PHONY : test/gradient.cpp.o

test/gradient.i: test/gradient.cpp.i
.PHONY : test/gradient.i

# target to preprocess a source file
test/gradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradient.dir/build.make CMakeFiles/test_gradient.dir/test/gradient.cpp.i
.PHONY : test/gradient.cpp.i

test/gradient.s: test/gradient.cpp.s
.PHONY : test/gradient.s

# target to generate assembly for a file
test/gradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradient.dir/build.make CMakeFiles/test_gradient.dir/test/gradient.cpp.s
.PHONY : test/gradient.cpp.s

test/lbfgs.o: test/lbfgs.cpp.o
.PHONY : test/lbfgs.o

# target to build an object file
test/lbfgs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/test/lbfgs.cpp.o
.PHONY : test/lbfgs.cpp.o

test/lbfgs.i: test/lbfgs.cpp.i
.PHONY : test/lbfgs.i

# target to preprocess a source file
test/lbfgs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/test/lbfgs.cpp.i
.PHONY : test/lbfgs.cpp.i

test/lbfgs.s: test/lbfgs.cpp.s
.PHONY : test/lbfgs.s

# target to generate assembly for a file
test/lbfgs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/test/lbfgs.cpp.s
.PHONY : test/lbfgs.cpp.s

test/linesearch.o: test/linesearch.cpp.o
.PHONY : test/linesearch.o

# target to build an object file
test/linesearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linesearch.dir/build.make CMakeFiles/test_linesearch.dir/test/linesearch.cpp.o
.PHONY : test/linesearch.cpp.o

test/linesearch.i: test/linesearch.cpp.i
.PHONY : test/linesearch.i

# target to preprocess a source file
test/linesearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linesearch.dir/build.make CMakeFiles/test_linesearch.dir/test/linesearch.cpp.i
.PHONY : test/linesearch.cpp.i

test/linesearch.s: test/linesearch.cpp.s
.PHONY : test/linesearch.s

# target to generate assembly for a file
test/linesearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linesearch.dir/build.make CMakeFiles/test_linesearch.dir/test/linesearch.cpp.s
.PHONY : test/linesearch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lbfgs_lib"
	@echo "... test_bfgs"
	@echo "... test_gradient"
	@echo "... test_lbfgs"
	@echo "... test_linesearch"
	@echo "... src/BFGS.o"
	@echo "... src/BFGS.i"
	@echo "... src/BFGS.s"
	@echo "... src/utils/LineSearch.o"
	@echo "... src/utils/LineSearch.i"
	@echo "... src/utils/LineSearch.s"
	@echo "... test/bfgs.o"
	@echo "... test/bfgs.i"
	@echo "... test/bfgs.s"
	@echo "... test/gradient.o"
	@echo "... test/gradient.i"
	@echo "... test/gradient.s"
	@echo "... test/lbfgs.o"
	@echo "... test/lbfgs.i"
	@echo "... test/lbfgs.s"
	@echo "... test/linesearch.o"
	@echo "... test/linesearch.i"
	@echo "... test/linesearch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

